# 2025/11/12 为方便和笔记库交互，不再自动执行此工作流，并将自动更新博客的工作流合并到笔记里的工作流

on:
  workflow_dispatch: {}
jobs:
  build:
    runs-on: docker
    container:
      image: m.daocloud.io/docker.io/node:lts-alpine
    steps:
      - name: 'setup build environment'
        run: |
          sed -i 's#https\?://dl-cdn.alpinelinux.org/alpine#https://mirror.nju.edu.cn/alpine#g' /etc/apk/repositories
          echo 'registry=https://mirrors.huaweicloud.com/repository/npm/' > ~/.npmrc
          apk add pandoc
          npm i -g pnpm

      - name: 'set timezone'
        run: |
          apk add tzdata
          cp -vf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          date
          
      - name: 'setup git and openssh'
        run: |
          apk add git openssh
          mkdir -p ~/.ssh/
          echo 'StrictHostKeyChecking no' >> ~/.ssh/config
          echo ${{ secrets.REPO_PRIVATE_KEY_BASE64 }} | base64 -d > ~/.ssh/id_ed25519
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/*
          git config --global user.name "bot"
          git config --global user.email "bot@oopsky.top"
          
      - name: 'clone repo'
        run: |
          echo '172.19.173.174 git.oopsky.top' >> /etc/hosts
          git clone ssh://git@git.oopsky.top:22222/${{ github.repository }}.git /workspace/${{ github.repository }}
          
      - name: 'build blog'
        run: |
          pnpm i
          pnpm hexo g

      - name: 'upload'
        run: |
          apk add openssh
          mkdir -p ~/.ssh
          echo 'LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNCckZ3eVNHdEQybjdlKys4c01NRWpSdDZIaGlWVUNNaHZSUEZrLzh4cGVUUUFBQUpqdXdhaVU3c0dvCmxBQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQnJGd3lTR3REMm43ZSsrOHNNTUVqUnQ2SGhpVlVDTWh2UlBGay84eHBlVFEKQUFBRUE4bmliOEtmbkQ4c2ZVVnV4UGFYRmdxTlJsNHdyaXg2Z2ROc0VVWFEvcndHc1hESklhMFBhZnQ3Nzd5d3d3U05HMwpvZUdKVlFJeUc5RThXVC96R2w1TkFBQUFFWEp2YjNSQVkyUTVOV0V3TURBeVlXUmhBUUlEQkE9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K' | base64 -d > ~/.ssh/id_ed25519
          echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGsXDJIa0Paft777ywwwSNG3oeGJVQIyG9E8WT/zGl5N root@cd95a0002ada' > ~/.ssh/id_ed25519.pub
          echo 'StrictHostKeyChecking no' > ~/.ssh/config
          echo 'UserKnownHostsFile /dev/null' > ~/.ssh/config
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/* 
          ssh -p 10022 root@172.19.173.174 rm -rf /data/*
          scp -P 10022 -r public/* root@172.19.173.174:/data/
