on: [push]
jobs:
  sync-repo:
    runs-on: docker
    container:
      image: m.daocloud.io/docker.io/node:lts-alpine
    steps:
      - name: 'setup build environment'
        run: |
          sed -i 's#https\?://dl-cdn.alpinelinux.org/alpine#https://mirror.nju.edu.cn/alpine#g' /etc/apk/repositories

      - name: 'set timezone'
        run: |
          apk add tzdata
          cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          
      - name: 'setup git and openssh'
        run: |
          apk add git openssh
          mkdir -p ~/.ssh/
          echo 'StrictHostKeyChecking no' >> ~/.ssh/config
          echo ${{ secrets.REPO_PRIVATE_KEY_BASE64_GH }} | base64 -d > ~/.ssh/id_ed25519
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/*

      - name: 'clone repo'
        run: |
          echo '172.19.173.174 git.oopsky.top' >> /etc/hosts
          git clone ssh://git@git.oopsky.top:22222/${{ github.repository }}.git /workspace/${{ github.repository }}

      - name: 'push to github'
        run: |
         git remote add github git@github.com:waleslau/blog_source.git
         git push github 
